# Generated by Django 4.2.20 on 2025-03-31 16:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_uploadpdf_pdf_key_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpdf',
            name='pdf_key',
            field=models.CharField(default=api.models.generateRandomKey, max_length=255, unique=True),
        ),
    ]
