# Generated by Django 4.2.20 on 2025-03-31 17:51

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_uploadpdf_pdf_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=api.models.generateRandomKey, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadpdf',
            name='pdf_key',
            field=models.CharField(default=api.models.generateRandomKey, max_length=36, unique=True),
        ),
    ]
