# Generated by Django 4.2.20 on 2025-03-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadpdf_user_user_user_id_alter_uploadpdf_pdf_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
