# Generated by Django 4.2.20 on 2025-05-05 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_note_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.uploadpdf'),
        ),
    ]
