# Generated by Django 4.2.20 on 2025-05-05 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_note_note_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='uploadpdf',
            options={'verbose_name': 'Upload PDF', 'verbose_name_plural': 'Upload PDFs'},
        ),
        migrations.AlterField(
            model_name='note',
            name='note_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_notes', to='api.uploadpdf'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadpdf',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pdfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
