# Generated by Django 4.2.20 on 2025-05-05 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_note_options_alter_uploadpdf_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_key',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_notes', to='api.uploadpdf'),
        ),
    ]
