# Generated by Django 4.2.20 on 2025-05-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_note_note_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcard_title', models.CharField(blank=True, max_length=255, null=True)),
                ('flashcard_question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='note_flashcards', to='api.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flashcards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='flashcard_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('flashcard_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_answers', to='api.flashcard')),
            ],
        ),
    ]
