# Generated by Django 4.2.20 on 2025-05-14 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_flashcard_flashcard_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='note_chat_messages', to='api.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
