# Generated by Django 4.2.20 on 2025-05-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
