# Generated by Django 4.2.20 on 2025-05-15 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chat_message_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='notebook_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notebooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notebook_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('note', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='note_notebook_notes', to='api.note')),
                ('notebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_notes', to='api.notebook_page')),
            ],
        ),
    ]
