# Generated by Django 4.2.20 on 2025-05-15 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notebook_page_notebook_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook_note',
            options={'verbose_name': 'Notebook Note', 'verbose_name_plural': 'Notebook Notes'},
        ),
        migrations.AddField(
            model_name='notebook_note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook_note',
            name='location_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='notebook_note',
            name='location_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='notebook_note',
            name='location_z',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='notebook_note',
            name='sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
