# Generated by Django 4.2.20 on 2025-05-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_notebook_note_options_notebook_note_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook_page',
            options={'verbose_name': 'Notebook Page', 'verbose_name_plural': 'Notebook Pages'},
        ),
    ]
