# Generated by Django 4.2.20 on 2025-05-21 04:09

from django.db import migrations, models
import uuid


def generate_uuid_for_existing_pages(apps, schema_editor):
    NotebookPage = apps.get_model('api', 'notebook_page')
    for page in NotebookPage.objects.all():
        page.page_id = uuid.uuid4()
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_notebook_page_options'),
    ]

    operations = [
        # First add the field as nullable
        migrations.AddField(
            model_name='notebook_page',
            name='page_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        # Then populate existing records
        migrations.RunPython(generate_uuid_for_existing_pages),
        # Finally make it non-nullable and unique
        migrations.AlterField(
            model_name='notebook_page',
            name='page_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
