# Generated by Django 4.2.20 on 2025-05-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notebook_page_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook_page',
            name='page_id',
        ),
    ]
